#https://github.com/KingRan/KR.git
name: KingRan
on:
  schedule:
    - cron: '0 */6 * * *' 
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-KingRan-KR
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync KingRan-KR 
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/KingRan/KR.git" 
          source_branch: "main" 
          destination_branch: "KingRan"  # #
          github_token: ${{ secrets.PAT }} 
          fetch-depth: 0
          path: "."
          exclude: "'icon','README.md'" 
